project:
  type: website

website:
  title: "MDS cheatsheets"
  navbar:
    left:
      - href: index.qmd
      - list.qmd
      # - block_1/511_python/511_python.md
      # - block_1/521_platforms/521_platforms.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
